# Generated by Django 5.1.1 on 2024-10-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charinfo',
            old_name='charID',
            new_name='char',
        ),
        migrations.RenameField(
            model_name='charinfo',
            old_name='userID',
            new_name='user',
        ),
    ]
