# Generated by Django 5.1.1 on 2024-10-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_charid_charinfo_char_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charinfo',
            old_name='ClassCount',
            new_name='classCount',
        ),
    ]
