# Generated by Django 5.1.1 on 2024-10-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_classcount_charinfo_classcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charinfo',
            name='searchDone',
            field=models.IntegerField(),
        ),
    ]
