# Generated by Django 5.1.1 on 2024-10-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.TextField()),
                ('itemImage', models.TextField()),
                ('itemCategory', models.TextField()),
                ('itemInfo', models.TextField()),
                ('itemPrice', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
